# ScriptBlockPlus v${project.version} Config #


## ===== 自動アップデート ===== ##
# [true -> 有効 | false -> 無効]
# 確認メッセージは"OP"にしか表示されません。
# 最新バージョンを確認するかどうか。
UpdateChecker: true

# 前提 "UpdateChecker: true"
# 最新のプラグインをダウンロードするかどうか。
AutoDownload: true

# 前提 "UpdateChecker: true"
# ダウンロードした更新内容を、メモ帳で開くかどうか。
OpenChangeLog: true

## ===== Json ===== ##
# [true -> 有効 | false -> 無効]
# リロード、サーバー起動時に全ファイルをキャッシュします。
# スムーズな動作が可能ですが、メモリを多く消費する可能性があります。
CacheAllJson: false

# JSONの整形を許可する要素数の上限を設定します。
# 上限を設定することで、容量の削減や処理速度の短縮が期待できます。
FormatLimit: 10000

## ===== スクリプトの並び替え ===== ##
# [true -> 有効 | false -> 無効]
# スクリプト実行時に推奨される順番通りにオプションを実行するかどうか。
# 設定されている優先順にオプションを並び替えて最適な順番で実行します。
SortScripts: true

## ===== コンソールログ ===== ##
# [true -> 有効 | false -> 無効]
# 言語ファイルの頭文字"console"が対象です。
# コンソールに操作メッセージ等を表示させることができます。
ConsoleLog: false

## ===== オプションヘルプ ===== ##
# [true -> 有効 | false -> 無効]
# タブ補完を行った際に、オプションのヘルプを表示するかどうか。
OptionHelp: true

## ===== オプション実行権限 ===== ##
# [true -> 有効 | false -> 無効]
# オプションを実行時に権限をチェックするかどうか。
OptionPermission: false

## ===== スクリプトの実行 ===== ##
# [true -> 有効 | false -> 無効]
# "左"または"右"クリックからのスクリプトの実行を無効化するかどうか。
Actions:
  # 左クリックの設定
  InteractLeft: true
  # 右クリックの設定
  InteractRight: true