# ScriptBlockPlus v${project.version} Config #

## ===== 自動アップデートの設定 ===== ##
# [true -> 有効 | false -> 無効]
# 確認メッセージは"OP"にしか表示されません。
# 最新バージョンを確認するかどうか。
UpdateChecker: true

# 前提 "UpdateChecker: true"
# 最新のプラグインをダウンロードするかどうか。
AutoDownload: true

# 前提 "UpdateChecker: true"
# ダウンロードした更新内容を、メモ帳で開くかどうか。
OpenChangeLog: true

## ===== 言語の設定 ===== ##
# 使用する言語を設定してください。
# 存在しない言語の追加方法は当プラグインのGithubをご覧ください。
# 固定 <default(簡易自動)>
# 一覧 <en(英語), ja(日本語), zh(中国語)>
Language: default

## ===== コンソールの設定 ===== ##
# [true -> 有効 | false -> 無効]
# 言語ファイルの頭文字"console"が対象です。
# コンソールに操作メッセージ等を表示させることができます。
ConsoleLog: false

## ===== スクリプト自動並び変えの設定 ===== ##
# [true -> 有効 | false -> 無効]
# スクリプト実行時に推奨される順番通りにオプションを実行するかどうか。
# 設定されている優先順にオプションを並び替えて、適正な順番で実行します。
SortScripts: true

## ===== オプション実行権限の設定 ===== ##
# [true -> 有効 | false -> 無効]
# オプションを実行時に権限をチェックするかどうか。
OptionPermission: false

## ===== コマンドセレクターの設定 ===== ##
# [true -> 有効 | false -> 無効]
# コマンドブロックと同様のセレクターを使用するかどうか。
# 対応プラットフォーム <CraftBukkit, Spigot, PaperMC>
# ※上記のサーバー以外は自動的に無効化されます。
CommandSelector: true

## ===== 左右クリックの設定 ===== ##
# [true -> 有効 | false -> 無効]
# "左"または"右"クリックからの実行を無効化するかどうか。
# 無効化した場合"@scriptaction"の使用に不備が出る場合がございます。
Actions:
  # 左クリックの設定
  InteractLeft: true
  # 右クリックの設定
  InteractRight: true